### ISSUE TITLE
Versionable_id force use of integer. What about models with protected $primary_key as varchar()?

### ISSUE THREAD

**Issue by gn0rt0n** [mpociot/versionable#10]
How could I use this if I have the following defined on a model:

```
class Product extends BaseModel
{
    protected $primaryKey = 'sku';
...
}

```

I have a few tables in my system that do not use integers as their primary key. It is not something I have the ability to change for these tables either, so they must remain varchar().

This constraint forces an integer. 

```
$table->integer('versionable_id');
```

**Comment by lukasoppermann** [comment]
Yes, for example when working with `uuid`s this will create an issue.
