### ISSUE TITLE
unserialize() expects parameter 1 to be string, resource given

### ISSUE THREAD

**Issue by williamoliveira** [mpociot/versionable#12]
I am receiving this error using Postgres:
```PHP warning:  unserialize() expects parameter 1 to be string, resource given in /my-project/vendor/mpociot/versionable/src/Mpociot/Versionable/Version.php on line 52```

I managed to get it working by changing Version's getModel() method with this before unserializing it:
```$modelData = is_resource($this->model_data)
            ? stream_get_contents($this->model_data)
            : $this->model_data;```

 do you know of a better way to get around it or can I make a PR with this fix?

**Comment by mpociot** [comment]
Yes - please create a PR for this.
