### ISSUE TITLE
Unable to load auth-model

### ISSUE THREAD

**Issue by anx-mwutte** [mpociot/versionable#19]
The Auth-Model in Version.php (method: "getResponsibleUserAttribute()") can't be loaded. The return value of the Config::get() method just returns "null".

In Laravel 5.3 the config option should be however "auth.providers.users.model" instead of just "auth.model".

So the method should be like this:

```
/**
 * Return the user responsible for this version
 * @return mixed
 */
public function getResponsibleUserAttribute()
{
    $model = Config::get('auth.providers.users.model');
    return $model::find($this->user_id);
}
```

**Comment by Harti** [comment]
Is this still an issue? I'm about to commence a new Laravel project and this would be a huge caveat.
