### ISSUE TITLE
Can migration command in documentatio be changed so it doesn't run migrations but move them to the migration folder with current date

### ISSUE THREAD

**Issue by dbr0** [mpociot/versionable#25]
Change:

`php artisan migrate --path=vendor/mpociot/versionable/src/migrations`

to something like

`cp vendor/mpociot.../migrations database/migrations` 

but also to update the dates in the filenames so they get ran when I run the `php artisan migrate` next time.

The way things are organized now are that I have to run this command whenever I move my code to another server. I had dev server for some time before going to staging and I completely forgot to run these migrations. I suppose the same thing will happen to me when I start the production server.

**Comment by mk-conn** [comment]
I think thats not very Laravel-ish...?  Why not writing just a script instead which handles all those mirgration stuff and also cache clearing after deploy?

**Comment by oschettler** [comment]
For packages, Laravel 5.4 has [loadMigrationsFrom()](https://laravel.com/docs/5.4/packages#migrations) to avoid calling `artisan migrate --path`.

**Comment by c-fitzmaurice** [comment]
This would be great if the migrations could be publishable with Laravel 5.4

**Comment by derhofbauer** [comment]
I created a pull request to cover this issue: https://github.com/mpociot/versionable/pull/34

**Comment by nonoesp** [comment]
Thanks! Closing as this was addressed with `loadMigrationsFrom` in #60. =)
