### ISSUE TITLE
Problem with multi connections

### ISSUE THREAD

**Issue by spresnac** [mpociot/versionable#35]
I have 2+x (client databases) db connections in my project.
I want to version only some of my models, but it always uses the default db connection.
Please change this, so that version uses the model db connection by default, where the "version" table is.

**Comment by spresnac** [comment]
I changed the "VersionableTrait.php" here
```
            $version                   = new $class();
            $version->versionable_id   = $this->getKey();
            $version->versionable_type = get_class($this);
```

to this

```
            $version                   = new $class();
            $version->setConnection($this->getConnection()->getName());
            $version->versionable_id   = $this->getKey();
            $version->versionable_type = get_class($this);
```

and it fit's my needs ;)

**Comment by spresnac** [comment]
see pr #36

**Comment by mpociot** [comment]
The version model is now configurable: https://github.com/mpociot/versionable/commit/9abd756eca24969eff85ff9f08cbce3afa991e0b#diff-8c6999c6977539530459d4be9a3a5150R10

I tagged a new version (3.1.0) with this fix

**Comment by spresnac** [comment]
Still my question: How to change the db-connection for a version on a model? It still uses the default connection, not the model one

**Comment by mpociot** [comment]
Now you can extend the version model that comes with this package, modify it's connection, and change it in the config file.
It will then use the connection that you specify on your extended version model.

**Comment by spresnac** [comment]
@mpociot Yes, works, thanks. Maybe a point for documentation ;)
