### ISSUE TITLE
Error when running migrations

### ISSUE THREAD

**Issue by joaosalless** [mpociot/versionable#4]
The command `php artisan migrate --package=mpociot/versionable` does not work on Laravel 5.1

Returns this error:
```
[RuntimeException]                      
The "--package" option does not exist.
```

Update the README file suggesting  `php artisan migrate --path=vendor/mpociot/versionable/src/migrations`

Thanks!

**Comment by brodkin** [comment]
+1

**Comment by BcTpe4HbIu** [comment]
+1

**Comment by mpociot** [comment]
Thanks, I updated the README :+1:
