### ISSUE TITLE
JSON columns with array cast are double encoded

### ISSUE THREAD

**Issue by hagabaka** [mpociot/versionable#43]
When a model has a "JSON array castable  field", for example by defining `protected $casts = ['field' => 'array']`, the stored versions will be **double** JSON encoded. For example, if the original model's column value was `{"a": "b"}`, the version's `getModel()` will have the column value `"{\"a\": \"b\"}"`.

This happens because when saving a version, `VersionableTrait::versionablePostSave()` uses `getAttributes()`, and when restoring a version, `Version::getModel()` uses `fill($attributes)`. `fill` will do conversions based on `$casts` (JSON encoding in this case), but `getAttributes` returns attributes as-is (already JSON-encoded string in this case). To fix this, `VersionableTrait::versionablePostSave()` should use `attributesToArray()` instead, which would return array castable columns as arrays, so that `fill()` works expectedly.

**Comment by PKuebler** [comment]
unfortunately we just got the bug. can we merge this PR?

thanks :)

**Comment by nonoesp** [comment]
Hi @hagabaka & @PKuebler - Will take a look!

**Comment by PKuebler** [comment]
@nonoesp , @mpociot any updates?

**Comment by nonoesp** [comment]
@PKuebler - Hi! For your use case, have you checked that #46 fixes the issue?

**Comment by PKuebler** [comment]
Yes, I changed the line locally in the vendor and it worked.

**Comment by nonoesp** [comment]
Just merged this pull request.
