### ISSUE TITLE
getModel() can only be called once.

### ISSUE THREAD

**Issue by merlinblack** [mpociot/versionable#64]
When getModel() is called again - the unserialize() call on line 56 of Version.php fails when model data is a resource.

stream_get_contents() in this case returns an empty string, as the stream has already been read.

Using: 
`stream_get_contents($this-model_data, -1, 0)`
i.e. a stream offset of zero returns the data every time - at least with Postgresql and php 7.4.5

**Comment by nonoesp** [comment]
Hey @merlinblack - Do you have any suggestions on how to fix this?

**Comment by merlinblack** [comment]
@nonoesp Sure - I've been experimenting. You can either use an offset with stream_get_contents, or call rewind before hand.

I'll make a PR.
