### ISSUE TITLE
Installation: migrations won't be executed

### ISSUE THREAD

**Issue by getriebesand** [mpociot/versionable#66]
Hi,

I want to use this package and followed the install instructions, but php artisan migrate says "Nothing to migrate."

I saw that the migrations are not loaded in the provider. It seems to break updates?
maybe you can use 
```
if (!Schema::hasTable('versions')) {
}
```
in the migration

**Comment by MarcelWeidum** [comment]
You can use `php artisan migrate --path=vendor/mpociot/versionable/src/migrations`

**Comment by nonoesp** [comment]
I'll revert the instructions (to [these ones](https://github.com/mpociot/versionable/blob/df21a81825531a70b50d62c08c9b263800f7a883/README.md) as @MarcelWeidum is showing). Automatic migrations were causing problems.

**Comment by MarcelWeidum** [comment]
I made a pull request [#67](https://github.com/mpociot/versionable/pull/67)

**Comment by nonoesp** [comment]
Thanks again!
