### ISSUE TITLE
[3.3.1] Migrations not working

### ISSUE THREAD

**Issue by Lumrenion** [mpociot/versionable#68]
With version 3.3.0 the custom migration command was substituted with 
```
$this->loadMigrationsFrom(__DIR__.'/../../../migrations');
```
in ServiceProvider. Therefore an update from 3.2.x to 3.3.0 was not possible because the migrations file was not added to the migrations table. When doing `php artisan migrate`, an error occurred as artisan tried to recreate the the versions table. (see #62)

In Version 3.3.1, above code was removed (see 6f5c542), therefore when you create a new project with the current version, migrations are not done at all and the plugin is not usable.

**Suggested fix:**
1. Add above code to ServiceProvider again
2. change migration file to check if table already exists before creating it.

**Comment by nonoesp** [comment]
Hi, @Lumrenion.

Thanks so much for your suggestion.

Can you post the error you're getting here?

**Comment by Lumrenion** [comment]
Hi @nonoesp 

You fixed it 10 days ago by changing the readme.md and added the migration command again. It seems I missed that.
```
php artisan migrate --path=vendor/mpociot/versionable/src/migrations
```
That one was missing in V3.3.1 and V3.3.2 bit it is currently in master.

So the bug is obsolete

**Comment by nonoesp** [comment]
Thanks for closing this @Lumrenion!
