### ISSUE TITLE
How to get the current version ID of a model?

### ISSUE THREAD

**Issue by royvdmaas** [mpociot/versionable#76]
This seems like a very simple question, but I don't see any documented option to get the current version ID. 

I currently use $model->versions()->count() to get the current version count, but this does not seem right and I can't use it to reference to retrieve the version of the model needed.

Thanks in advance!

Roy

**Comment by nonoesp** [comment]
Hi, @royvdmaas! I believe you might be looking for this.

```php
$model->currentVersion()->version_id
```

**Comment by royvdmaas** [comment]
Knew this should've been easy! Thank you!
